2025-04-15 19:07:42 | ERROR | cli.shell:do_diff:18 - An error has been caught in function 'do_diff', process 'MainProcess' (2228), thread 'MainThread' (8428963904):
Traceback (most recent call last):

  File "/opt/homebrew/Caskroom/miniconda/base/bin/comitpal", line 8, in <module>
    sys.exit(app())
    │   │    └ <function app at 0x1016a98a0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/comitpal_core/main.py", line 8, in app
    ComitPal().cmdloop()
    └ <class 'cli.shell.ComitPal'>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           │    │      └ 'diff'
           │    └ <function Cmd.onecmd at 0x1037c37e0>
           └ <cli.shell.ComitPal object at 0x10161aa80>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/cmd.py", line 217, in onecmd
    return func(arg)
           │    └ ''
           └ <bound method ComitPal.do_diff of <cli.shell.ComitPal object at 0x10161aa80>>
> File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/cli/shell.py", line 18, in do_diff
    commit_message = generate_commit_message(git_diff)
                     │                       └ 'diff --git a/_posts/2025-04-07-skillz.md b/_posts/2025-04-07-skillz.md\nindex 1b6ea37..9b60126 100644\n--- a/_posts/2025-04-...
                     └ <function generate_commit_message at 0x1037c23e0>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/utils/services.py", line 18, in generate_commit_message
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
             │            │  │       └ <function Mapping.get at 0x1015ee2a0>
             │            │  └ environ({'PWD': '/Users/hardikjaiswal/Documents/pythonicforge.github.io', 'CONDA_PYTHON_EXE': '/opt/homebrew/Caskroom/minicon...
             │            └ <module 'os' (frozen)>
             └ <class 'groq.Groq'>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/groq/_client.py", line 84, in __init__
    raise GroqError(
          └ <class 'groq.GroqError'>

groq.GroqError: The api_key client option must be set either by passing api_key to the client or by setting the GROQ_API_KEY environment variable
2025-04-15 19:07:42 | SUCCESS | cli.shell:do_diff:20 - Commit message generated!
2025-04-15 19:08:27 | INFO | cli.shell:do_bye:37 - Shutting down commitpal..
2025-04-15 19:08:27 | SUCCESS | cli.shell:do_bye:38 - Done
2025-04-15 19:08:30 | ERROR | cli.shell:do_diff:18 - An error has been caught in function 'do_diff', process 'MainProcess' (2270), thread 'MainThread' (8428963904):
Traceback (most recent call last):

  File "/opt/homebrew/Caskroom/miniconda/base/bin/comitpal", line 8, in <module>
    sys.exit(app())
    │   │    └ <function app at 0x1050558a0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/comitpal_core/main.py", line 8, in app
    ComitPal().cmdloop()
    └ <class 'cli.shell.ComitPal'>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           │    │      └ 'diff'
           │    └ <function Cmd.onecmd at 0x1071677e0>
           └ <cli.shell.ComitPal object at 0x104fc6a80>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/cmd.py", line 217, in onecmd
    return func(arg)
           │    └ ''
           └ <bound method ComitPal.do_diff of <cli.shell.ComitPal object at 0x104fc6a80>>
> File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/cli/shell.py", line 18, in do_diff
    commit_message = generate_commit_message(git_diff)
                     │                       └ 'diff --git a/_posts/2025-04-07-skillz.md b/_posts/2025-04-07-skillz.md\nindex 1b6ea37..9b60126 100644\n--- a/_posts/2025-04-...
                     └ <function generate_commit_message at 0x1071663e0>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/utils/services.py", line 18, in generate_commit_message
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
             │            │  │       └ <function Mapping.get at 0x104f9a2a0>
             │            │  └ environ({'PWD': '/Users/hardikjaiswal/Documents/pythonicforge.github.io', 'CONDA_PYTHON_EXE': '/opt/homebrew/Caskroom/minicon...
             │            └ <module 'os' (frozen)>
             └ <class 'groq.Groq'>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/groq/_client.py", line 84, in __init__
    raise GroqError(
          └ <class 'groq.GroqError'>

groq.GroqError: The api_key client option must be set either by passing api_key to the client or by setting the GROQ_API_KEY environment variable
2025-04-15 19:08:30 | SUCCESS | cli.shell:do_diff:20 - Commit message generated!
2025-04-15 19:10:52 | INFO | cli.shell:do_bye:37 - Shutting down commitpal..
2025-04-15 19:10:52 | SUCCESS | cli.shell:do_bye:38 - Done
2025-04-15 19:11:12 | INFO | utils.services:generate_commit_message:36 - Generating commit message...
2025-04-15 19:11:12 | SUCCESS | cli.shell:do_diff:20 - Commit message generated!
2025-04-15 19:11:18 | INFO | utils.services:generate_commit_message:36 - Generating commit message...
2025-04-15 19:11:19 | SUCCESS | cli.shell:do_diff:20 - Commit message generated!
2025-04-15 19:11:19 | INFO | utils.services:auto_push_to_github:89 - Staging changes...
